return {
  "drums", "guitar", "glass", "book", "magazine", "sink", "pillow", "shoe", "couch",
  "view", "eye", "cousin", "brother", "sister", "newspaper", "mother", "father",
  "blanket", "curtain", "pencil", "grandmother", "grandfather", "black", "white", "red",
  "green", "blue", "yellow", "purple", "orange", "violet", "light", "dark", "circle",
  "big", "small", "huge", "tiny", "lamp", "star", "clock", "candle", "carpet", "game",
  "keyboard", "war", "peace", "sock", "trousers", "computer", "phone", "chair", "table",
  "plant", "wardrobe", "closet", "board", "library", "sea", "ocean", "ground", "sun",
  "moon", "sky", "fast", "slow", "exclamation", "mark", "plan", "now", "bookmark", "tooth",
  "out", "in", "outside", "inside", "television", "turn", "cloth", "delivery", "basket",
  "watch", "hand", "finger", "foot", "stomach", "paw", "leg", "number", "form", "bunker",
  "beer", "special", "funny", "laugh", "certain", "elephant", "giraffe", "dog", "cat",
  "bird", "swan", "wolf", "hammer", "screwdiver", "screw", "fish", "meat", "vegetable",
  "fruit", "potato", "lemonade", "lemon", "win", "lose", "amazing", "incredible", "fantastic",
  "panda", "bear", "polar", "center", "middle", "left", "right", "sell", "sick", "ill",
  "crazy", "health", "apple", "peer", "apricot", "onion", "sauce", "kitchen", "soup", "eat",
  "prepare", "really", "walk", "run", "go", "door", "open", "close", "handle", "carrot",
  "dig", "pick", "fall", "sleep", "bed", "love", "leave", "study", "university", "school",
  "class", "local", "global", "machine", "wheel", "broom", "bath", "bathroom", "room",
  "bedroom", "good", "bad", "i", "you", "he", "she", "we", "they", "shirt", "vacuum",
  "cleaner", "week", "weekend", "day", "journey", "monday", "tuesday", "wednesday", 
  "thursday", "friday", "saturday", "sunday", "music", "song", "album", "screen", "chalk",
  "person", "everything", "goal", "live", "life", "rock", "arm", "meet", "morning", "evening",
  "night", "breakfast", "help", "listen", "hear", "promise", "tomorrow", "cave", "basement",
  "toilet", "light", "face", "tie", "time", "money", "coin", "other", "dentist", "baker",
  "butcher", "man", "women", "nothing", "wash", "super", "great", "null", "smart", "how",
  "why", "where", "when", "dish", "meal", "pleasure", "field", "key", "character", "smoke",
  "coffee", "place", "first", "last", "movie", "cinema", "message", "come", "happy",
  "replacement", "pen", "plastic", "cleaning", "bicycle", "station", "train", "yes", "no",
  "look", "target", "hour", "mug", "plate", "bowl", "cereal", "debt", "bill", "banana",
  "garlic", "partial", "integer", "semi", "part", "fraction", "equation", "experiment",
  "experience", "remark", "sound", "spice", "salt", "pepper", "manual", "oven", "trash",
  "speak", "word", "voice", "verb", "adjective", "decode", "encode", "empty", "sit", "tea",
  "battery", "analysis", "variable", "line", "code", "hello", "hi", "note", "speed", "weight",
  "width", "height", "pride", "student", "nail", "uncle", "pyramid", "tower", "turn", "wall",
  "jacket", "happiness", "sadness", "angry", "anger", "dust", "print", "feeling", "quarter",
  "home", "house", "digit", "melody", "sheet", "piano", "trumpet", "saxophone", "zebra",
  "rabbit", "hat", "parenthesis", "curve", "graphics", "theory", "usage", "scarf", "practice",
  "illness", "disease", "violin", "quality", "default", "genius", "information", "touch",
  "flower", "petal", "also", "however", "otherwise", "rather", "doctor", "nurse", "knowledge",
  "rail", "carry", "common", "intern", "extern"
}
