return {
  "tambour", "guitare", "verre", "livre", "magazine", "évier", "oreiller", "chaussure",
  "fauteuil", "vue", "oeil", "coussin", "cousin", "frère", "soeur", "journal", "mère",
  "père", "couverture", "crayon", "grand-mère", "grand-père", "branlix", "noir", "blanc",
  "rouge", "vert", "bleu", "jaune", "violet", "orange", "mauve", "clair", "sombre",
  "cerk", "grand", "petit", "lampe", "étoile", "horloge", "bougie", "tapis", "jeu",
  "clavier", "guerre", "paix", "chaussette", "pantalon", "ordinateur", "mobile", "chaise",
  "table", "plante", "armoire", "tableau", "bump", "mer", "océan", "sol", "soleil", "lune",
  "astre", "ciel", "rapide", "lent", "exclamation", "plan", "maintenant", "marque-page",
  "dent", "dehors", "dedans", "télévision", "allumer", "éteindre", "nappe", "livraison",
  "panier", "montre", "main", "doigt", "pied", "ventre", "patte", "jambe", "numéro",
  "forme", "bunker", "bière", "spécial", "marrant", "certain", "éléphant", "girafe",
  "chien", "chat", "oiseau", "cygogne", "loup", "marteau", "tourne-vis", "vis", "poisson",
  "viande", "légume", "fruit", "couz", "frite", "limonade", "citron", "gagner", "incroyable",
  "fantastique", "panda", "ours", "polaire", "centre", "milieu", "gauche", "droite",
  "prévente", "malade", "fou", "santé", "caniche", "patate", "pomme", "poire", "abricot",
  "oignon", "échalotte", "sauce", "cuisine", "soupe", "manger", "préparer", "vraiment",
  "marcher", "courir", "rentrer", "porte", "ouverture", "poignée", "calotte", "ramasser",
  "tomber", "dormir", "lit", "aimer", "partir", "étude", "université", "cours", "local",
  "pompe", "pot", "roue", "balais", "raclette", "bain", "salle", "bien", "mal", "étonnant",
  "je", "tu", "il", "nous", "vous", "ils", "elle", "elles", "chemise", "aspirateur",
  "semaine", "jour", "journée", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "musique",
  "chanson", "album", "écran", "couverture", "craie", "personne", "tout", "but", "vivre",
  "pierre", "bras", "rencontre", "matin", "soir", "déjeuner", "aide", "écouter", "promettre",
  "demain", "cave", "toilette", "lumière", "face", "argent", "pièce", "monnaie", "autre",
  "dentiste", "boulanger", "boucher", "patisserie", "annonce", "homme", "femme", "rien",
  "laver", "super", "nul", "malin", "comment", "repas", "plaisir", "champ", "clé", "caractère",
  "franchement", "fumer", "machine", "café", "endroit", "fois", "premier", "dernier", "film",
  "cinéma", "message", "revenir", "content", "remplacement", "stylo", "plastique", "nettoyage",
  "vélo", "métro", "train", "ouvrir", "fermer", "oui", "non", "regarder", "rangement",
  "tourner", "cible", "heure", "cruche", "tasse", "assiette", "bol", "céréale", "dette",
  "banane", "poireau", "ail", "partiellement", "entier", "demi", "partie", "fraction",
  "calcul", "équation", "expérience", "remarquer", "son", "épice", "sel", "poivre", "manuel",
  "four", "poubelle", "canapé", "parole", "mot", "voix", "verbe", "adjectif", "décoder",
  "encoder", "vider", "asseoir", "thé", "batterie", "analyse", "bougie", "variable", "ligne",
  "code", "bonjour", "note", "vitesse", "poids", "hauteur", "largeur", "longueur", "orgueil",
  "vaisselle", "étudiant", "ongle", "oncle", "pyramide", "tour", "mur", "rire", "veste",
  "manteau", "bonheur", "malheur", "joie", "tristesse", "colère", "poussière", "impression",
  "siège", "quartier", "maison", "trajet", "nombre", "chiffre", "téléphone", "mélodie",
  "partition", "piano", "trompette", "saxophone", "xylophone", "zèbre", "lapin", "chapeau",
  "parenthèse", "plateau", "courbe", "graphique", "théorie", "pratique", "écharpe", "maladie",
  "violon", "vice", "qualité", "défaut", "génial", "info", "chigé", "math", "bio", "toucher",
  "fleur", "pétale", "marrant", "aussi", "également", "médecin", "docteur", "savoir", "rail",
  "porter", "commun", "interne", "externe", "intérieur", "extérieur", "alaid"
}
